version: "3.8"

services:
  transcriber:
    build:
      context: ./transcriber
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./transcriber:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/geshi
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  summarizer:
    build:
      context: ./summarizer
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./summarizer:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/geshi
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build:
      context: ./geshi/ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./geshi/ui:/app
    depends_on:
      - transcriber
      - summarizer
    command: npm start

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geshi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
