export type {
  AcquiredAsset,
  JsonObject,
  JsonValue,
  ObservedAsset,
  ObservedContent,
  PluginCapability,
  PluginLogger,
  PluginManifest,
  SourceCollectorAcquireInput,
  SourceCollectorInspectError,
  SourceCollectorInspectErrorCode,
  SourceCollectorInspectInput,
  SourceCollectorObserveInput,
  SourceCollectorObserveResult,
  SourceCollectorPlugin,
  SourceCollectorPluginCapability,
  SourceCollectorPluginDefinition,
  SourceCollectorSourceKind,
  SourceMetadata,
} from "@geshi/plugin-api";
