name: Check Commit Messages on PR

on:
  pull_request:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pushed branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }}
      - name: Check commit messages
        shell: bash
        run: |
          echo "🔍 Checking PR commits..."
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:'%s' | while read subject || [ -n "$subject" ]; do
            echo "→ $subject"
            if echo "$subject" | grep -qE '^:.*: '; then
              continue
            elif echo "$subject" | grep -qE '^Merge pull request #[0-9]+ from '; then
              continue
            elif echo "$subject" | grep -qE '^Merge [0-9A-Fa-f]+ into [0-9A-Fa-f]+'; then
              continue
            else
              echo "❌ Invalid commit message format: '$subject'"
              exit 1
            fi
          done
