name: Transcriber PR Checks

on:
  pull_request:
    branches: [master]
    paths:
      - "transcriber/**"

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.12.7"
          cache: "pip"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: transcriber
        run: poetry install

      - name: Format check with black
        working-directory: transcriber
        run: poetry run black --check .

      - name: Format check with isort
        working-directory: transcriber
        run: poetry run isort --check .

      - name: Type check with mypy
        working-directory: transcriber
        run: poetry run mypy .

      - name: Test with pytest
        working-directory: transcriber
        run: poetry run pytest
